### ISSUE TITLE
custom validation profile loading not working in aml example

### ISSUE THREAD

**Issue by yungcheng** [aml-org/amf#1062] opened 2021-07-29 15:27 UTC
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**
See the example here
https://github.com/aml-org/examples/blob/master/AMF4/src/test/js/validation.test.js#L28

The file path in the test is outdated but even after I updated the file path in this PR
https://github.com/aml-org/examples/pull/26

The test is still failing because of the following error
```
● Validate RAML 1.0 with custom validation

    Failed: bc {
      "Hg": null,
      "SJa": true,
      "Xs": "Cannot load a custom validation profile for this",
      "ZX": null,
      "stackdata": [Circular],
    }
```

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

* **What is the expected behavior?**
That example test should pass

* **What is the motivation/use case for changing the behavior? (for feature requests)**
We have a similar custom validation profile step setup and is now broken after upgrading from `4.2.0` to `4.7.5`

* **Please tell us about your environment:**
https://github.com/aml-org/examples/blob/master/AMF4/package.json#L18  

  - AMF Version: "4.8.0-SNAPSHOT.2", also tried on "4.7.5"
  - AMF Distribution: JS 
  - Operating System: Mac OS X
  - Link to your project: https://github.com/aml-org/examples

**Comment by arielmirra** [comment] 2021-07-29 22:27
Hi @yungcheng! Thank you for bringing that up! I've done some research into it and:
- I've already fixed the paths issue in AMF 4 in [this PR](https://github.com/aml-org/examples/pull/27)
- I've reproduced and confirmed that the custom validation example doesn't work (AMF doesn't apply the validation profile) and created an internal issue: https://www.mulesoft.org/jira/browse/APIMF-3302
- You can avoid that strange message in the report if you log it using `report.toString()`. That will show you the full report and why amf is throwing an error.

Unfortunately, AMF 4 is in maintenance mode and the bug will not have a high priority. Please consider using [AMF 5](https://github.com/aml-org/examples/tree/master/AMF5/src/test/ts) to have continuous support, simpler interfaces, and more features in the future. We're still in beta but we'll release soon, you can find all the examples of AMF 5 [here](https://github.com/aml-org/examples/tree/master/AMF5/src/test).

**Comment by AgustinBettati** [comment] 2021-12-27 21:04
Hello @yungcheng!
Tried this test with the current state of AMF 4 examples using AMF 4.7.8 and the custom validation test case is working correctly. Closing this issue but feel free to comment if you cannot reproduce this behaviour.

Relevant to this topic, take into consideration that the newest version of AMF  no longer supports this functionality natively in the library. More details under **Discontinued support of custom validation functionality** in https://github.com/aml-org/amf/releases/tag/5.0.0.

**Closed as completed by AgustinBettati** 2021-12-27 21:04 UTC
Labels: internal issue
