### ISSUE TITLE
OAS 2.0 to RAML 1.0 conversion missing `type:` under `application/json:`

### ISSUE THREAD

**Issue by yungcheng** [aml-org/amf#1061] opened 2021-07-29 15:21 UTC
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Sample swagger.json snippet
```json
{
  "paths": {
        "/pet/{petId}": {
            "get": {
                "description": "Returns a single pet",
                "operationId": "getPetById",
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": { "$ref": "#/definitions/Pet" }
                    }
                }
            }
        }
    }
}
```

Expected Output
```yaml
/pet/{petId}:
  get:
    displayName: getPetById
    description: Returns a single pet
    (amf-produces):
      - application/json
    responses:
      '200':
        description: successful operation
        body:
          application/json:
            type: Pet
```
Actual output
(Notice that `Pet` is inlined instead of under `type: Pet`)
```raml
/pet/{petId}:
  get:
    displayName: getPetById
    description: Returns a single pet
    (amf-produces):
      - application/json
    responses:
      "200":
        description: successful operation
        body:
          application/json: Pet
```

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

my conversion logic
```js
import * as amf from 'amf-client-js';
import * as fs from 'fs';

export async function parse(path) {
    amf.plugins.document.WebApi.register();
    amf.plugins.document.Vocabularies.register();
    amf.plugins.features.AMFValidation.register();

    // Initialize the AMF library
    await amf.AMF.init();

    const jsonParser = new amf.Oas20Parser();
    const yamlParser = new amf.Oas20YamlParser();
    const resolver = new amf.Raml10Resolver();
    const renderer = new amf.Raml10Renderer();
    let parsedModel = null;
    let outputPath = null;

    const ext = path.split('.').pop();
    switch (ext) {
        case 'json':
            parsedModel = await jsonParser.parseFileAsync(`file://${path}`);
            outputPath = path.replace('.json', '.raml');
            break;
        case 'yaml':
            parsedModel = await yamlParser.parseFileAsync(`file://${path}`);
            outputPath = path.replace('.yaml', '.raml');
            break;
    }

    const converted = await resolver.resolve(
        parsedModel,
        amf.ResolutionPipeline.COMPATIBILITY_PIPELINE
    );
    const result = await renderer.generateString(converted);
    fs.writeFileSync(`${outputPath}`, result);

    return Promise.resolve();
}
```

* **What is the expected behavior?**
```
        body:
          application/json:
            type: Pet
```

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.5
  - AMF Distribution: JS 
  - Operating System: Mac OS X
  - Link to your project: https://github.com/yungcheng/luvio/tree/parse-open-api

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

Based on examples in the document [here](https://github.com/mulesoft/oas-raml-converter/blob/master/docs/OAS20-to-RAML10.md), I would expect this being a bug and the response entity type should not be inlined but specified under `application/json:` with `type:`

**Comment by arielmirra** [comment] 2021-07-29 22:34
Hi @yungcheng! This is not a bug. The output API is a valid RAML and is equivalent to the expected output, both in RAML and in the AMF model. I'm closing this issue but feel free to ask anything.

Also, the project you linked is currently private. If you're using AMF, consider adopting the AMF 5 version.

Thank you!

**Closed as completed by arielmirra** 2021-07-29 22:34 UTC
