### ISSUE TITLE
Invalid scalar inheritance base type when specializing int64 type

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1736] opened 2023-03-05 23:58 UTC
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**

When attempting to narrow `int64` to `int32`, invalid type inheritance occurs.

The following RAML reproduces the issue:
```yaml
#%RAML 1.0 Library

types:
  IntObject:
    properties:
      prop1: Int64Type

  DerivedIntObject:
    type: IntObject
    properties:
      prop1: Int32Type

  Int64Type:
    type: integer
    format: int64

  Int32Type: # Throws "Resolution error: Invalid scalar inheritance base type http://www.w3.org/2001/XMLSchema#integer < http://www.w3.org/2001/XMLSchema#long (http://a.ml/vocabularies/amf/resolution#invalid-type-inheritance)"
    type: integer
    format: int32
```

Is this done on purpose or can this case be considered as bug?

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.4
  - AMF Distribution: JVM and JS
  - Operating System: Windows 10 22H2

**Comment by arielmirra** [comment] 2023-03-09 18:45
hi @deiteris! This is a bug, but this issue is related to inheritance resolution, and we're going through a big refactor in that regard. Therefore, I've created an [internal issue](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001MsDmNYAV/view) but put it on hold until this is done. I'll take some time, we'll update you when it's done.

**Comment by looseale** [comment] 2023-11-03 13:16
Hi! 
The issue is fixed with [this commit](https://github.com/aml-org/amf/commit/d99259eef6b35e0a954b1b49428d0f8ffe8c1f0d) and it will be released in the next version (ETA November 15th).
It will show a warning `different values for format constraint` for the format override (this is an expected behavior), but the violation message about the inheritance is fixed and it is computed correctly.

**Closed as completed by looseale** 2023-11-03 13:16 UTC
Labels: internal issue
