### ISSUE TITLE
Not able to find readable object for Channels,Components and payloads.

### ISSUE THREAD

**Issue by mkmishra89** [aml-org/amf#1841] opened 2023-08-02 05:30 UTC
Hi Team,

We are trying to parse asynApi but not able to find readable object for channels, component and payloads. Could you please help for the same. It is blocker for us.

Please find the below asyncAPI for your refrences.

{
    "asyncapi": "2.0.0",
    "spec-version": "1.0",
    "info": {
        "title": "Test",
        "version": "1.0",
        "description": "Test Description"
    },
    "x-api-type": "EVENT",
    "x-shortText": "information details",
    "x-stateInfo": {
        "state": "active"
    },
    "channels": {
        "ce/test/t4/test1/test2/v1/test3/Changed/v1": {
            "subscribe": {
                "message": {
                    "description": "Description.",
                    "$ref": "#/components/messages/test_t4_test1_test2_v1_test3_Changed_v1"
                }
            }
        }
    },
    "components": {
        "messages": {
            "test_t4_test1_test2_v1_test3_Changed_v1": {
                "name": "test_t4_test1_test2_v1_test3_Changed_v1",
                "summary": "summary",
                "description": "dDscription",
                "headers": {
                    "properties": {
                        "type": {
                            "const": "test_t4_test1_test2_v1_test3_Changed_v1"
                        },
                        "source": {
                            "const": ""
                        },
                        "datacontenttype": {
                            "const": "application/json"
                        }
                    }
                },
                "payload": {
                    "$ref": "#/components/schemas/test1_t4_beh_test2_v1_test3_Changed_v1"
                },
                "traits": [
                    {
                        "$ref": "#/components/messageTraits/testContext"
                    }
                ]
            }
        },
        "schemas": {
            "test1_t4_beh_test2_v1_test3_Changed_v1": {
                "type": "object",
                "properties": {
                    "AllergenInternalID": {
                        "type": "string"
                    }
                }
            }
        },
        "messageTraits": {
            "testContext": {
                "headers": {
                    "type": "object",
                    "properties": {
                        "specversion": {
                            "description": "Description",
                            "type": "string",
                            "const": "1.0"
                        },
                        "type": {
                            "description": "Description",
                            "type": "string",
                            "minLength": 1
                        },
                        "source": {
                            "description": "Description",
                            "type": "string",
                            "format": "uri-reference"
                        },
                        "subject": {
                            "description": "Description",
                            "type": "string",
                            "minLength": 1
                        },
                        "id": {
                            "description": "Description",
                            "type": "string",
                            "minLength": 1,
                            "examples": [
                                "QgEK7wzuHtqdhJwqCS+VOA=="
                            ]
                        },
                        "time": {
                            "description": "Description",
                            "type": "string",
                            "format": "date-time",
                            "examples": [
                                "2018-04-05T17:31:00Z"
                            ]
                        },
                        "datacontenttype": {
                            "description": "Description",
                            "type": "string",
                            "const": "application/json"
                        }
                    },
                    "required": [
                        "id",
                        "specversion",
                        "source",
                        "type"
                    ]
                }
            }
        }
    },
    "externalDocs": {
        "description": "Description",
        "url": "https://help.sap.com/http.svc/ahp2/SAP_S4HANA_ON-PREMISE/2022.002/EN/30/96e09c79e24457b76ebdcaec944054/frameset.htm"
    }
}

**Comment by tomsfernandez** [comment] 2023-08-02 14:59
Hi @mkmishra89 can you share a code example with us of how you are attempting to read this? Please remember to use the bug template so that we can help you faster.

**Comment by mkmishra89** [comment] 2023-08-03 04:27
Hi Tomas,

this is how we are using to parse the file.

final AMFBaseUnitClient asynchclient = AsyncAPIConfiguration.Async20().baseUnitClient();
final BaseUnit asynchUnresolvedModel =
asynchclient.parse("file://src/test/resources/testSchemas/reqRes/Test.json").get().baseUnit();
final BaseUnit asynchResolvedModel = asynchclient.transform(asynchUnresolvedModel).baseUnit();
final Document asynchDocument = (Document) asynchResolvedModel;
AsyncApi encodes = (AsyncApi) asynchDocument.encodes();
encodes.endPoints().forEach(endPoint -> {
endPoint.operations().forEach(operation -> {
System.out.println(operation.method().value());

		});
	});
==================
And another one also we tried:

final AMFBaseUnitClient client = APIConfiguration.API().baseUnitClient();
final AMFParseResult parseResult = client.parseContent("src/test/resources/testSchemas/reqRes/OP_ALLERGENEVENTS.json").get();
final BaseUnit model = parseResult.baseUnit();
final DomainElement asyncApi = ((Document) model).encodes();

**Comment by mkmishra89** [comment] 2023-08-04 05:20
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment] 2023-08-07 03:55
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment] 2023-08-08 03:04
Hi Team,

Gentle Reminder !!

Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment] 2023-08-09 03:29
@tomsfernandez ,

Could you please look above issue. We are blocked due this.


Thanks,
Mukesh Mishra

**Comment by mkmishra89** [comment] 2023-08-09 04:57
@fmvilas
Fran Méndez

We are trying to parse AsyncApi but are having trouble. Could you perhaps assist us? The information mentioned above.

Thanks in advance

Regards,
Mukesh Mishra

**Comment by tomsfernandez** [comment] 2023-08-10 17:52
Duplicate of https://github.com/aml-org/amf/issues/1848. Closing

**Closed as completed by tomsfernandez** 2023-08-10 17:52 UTC
